language: c
install: test -e .travis-opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11
  - OCAML_VERSION=4.12
  - OCAML_VERSION=4.13
  - OCAML_VERSION=4.14
  - OCAML_VERSION=5.00
  - OCAML_VERSION=5.01
  - OCAML_VERSION=5.02
  - OCAML_VERSION=5.03
  - OCAML_VERSION=5.04
os:
  - freebsd
  - linux
  - osx
arch:
  - amd64
  - arm64
